# Generated by Django 3.2.9 on 2023-03-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20230321_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='detdate',
            new_name='duedate',
        ),
    ]
